version: '3.2'
services:
  phpunit:
    image: phpunit/phpunit:latest
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
  php53: 
    image: devilbox/php-fpm:5.3-mods
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
  php55:
    image: devilbox/php-fpm:5.5-mods
    #build:
    #  context: ./../images/kimantaV3
    #  dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./vendor:/var/www/html/vendor
  mysql:
    image: mysql:5.7 
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro